-- MySQL Script generated by MySQL Workbench
-- 12/05/17 11:24:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema logs
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `logs` ;

-- -----------------------------------------------------
-- Schema logs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logs` DEFAULT CHARACTER SET utf8 ;
USE `logs` ;

-- -----------------------------------------------------
-- Table `logs`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logs`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(128) NOT NULL,
  `created_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
